export const ADD_ALERT_MESSAGE = 'ADD_ALERT_MESSAGE';
export const SET_ALERT_TYPE = 'SET_ALERT_TYPE';
export const TOGGLE_ALERT = 'TOGGLE_ALERT';
export const OPEN_NEW_ALERT = 'OPEN_NEW_ALERT';

export const SET_SETTINGS = 'SET_SETTINGS';
export const DELETE_SETTING = 'DELETE_SETTING';
export const CHANGE_SETTING = 'CHANGE_SETTING';
export const ADD_SETTING = 'ADD_SETTING';

export const TOGGLE_CONSOLE = 'TOGGLE_CONSOLE';
export const RUN_PROVISIONING = 'RUN_PROVISIONING';
